{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\"}[10m])) * 60",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\", method=\"GET\"}[10m])) * 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\", method=\"DELETE\"}[10m])) * 60",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\", method=\"POST\"}[10m])) * 60",
     "legendFormat": "Post"
    },
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\", method=\"PUT\"}[10m])) * 60",
     "legendFormat": "Put"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "active_users_count{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Service Latency (ms)"
    }
   ]
  },
  {
   "title": "Average Order Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "order_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Ordering Latency (ms)"
    }
   ]
  },
  {
   "title": "Pizza Creation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_count_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizzas Sold/minute"
    },
    {
     "expr": "rate(orders_failed_count_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Pizza Order Failure/minute"
    }
   ]
  },
  {
   "title": "Revenue BTC/minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_BTC_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "BITCOIN Revenue"
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Attempts/minute",
   "type": "timeseries",
   "description": "Only tracks when the system authenticates a token. Doesn't include logging in.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(auth_successes_count_total{source=\"jwt-pizza-service\"}[5m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(auth_failures_count_total{source=\"jwt-pizza-service\"}[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}